# Generated by Django 6.0.5 on 2026-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_match_away_team_match_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='goal_records',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='highest_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='lineup_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='match_info_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='score_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='team_stats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='max_speed',
            field=models.FloatField(default=0),
        ),
    ]
