# Generated by Django 6.0.5 on 2026-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_analysisresult_analysis_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='analyzer_team_ids',
            field=models.TextField(blank=True),
        ),
    ]
