# Generated by Django 6.0.5 on 2026-06-05 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_analysisresult_analyzer_team_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerresult',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.player'),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='track_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='track_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
