# Generated by Django 6.0.5 on 2026-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisresult_playerresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='video_name',
            field=models.CharField(default='전반전', max_length=100),
        ),
    ]
